- name: set up catalogue serve
  hosts: catalogue
  become: yes
  tasks: 
  - name: disbale default nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable latest nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y


  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: create user
    ansible.builtin.user:
      name: roboshop
      comment: Roboshop system user
      system: true
      shell: /sbin/nologin
      home: /app

  - name: create app directory
    ansible.builtin.file:
      state: directory
      path: /app
      
  - name: download the file
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: extact catalogue
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  
  - name: install depenedencies
    community.general.npm:
      path: /app

  - name: copy catalogue services
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  
  - name: copy mongorepp
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb clinet
    ansible.builtin.package:
      name: mongodb-mongosh
      state: present

  # - name: connect to mongo db catalogue
  #   ansible.builtin.command: mongosh mongodb.thiscomeback.fun --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  #   register: catalogue_output
  
  - name: evalute the catalogue database
    community.mongodb.mongodb_shell:
      eval: db.getMongo().getDBNames().indexOf('catalogue')
    register: catalogue_output



  - name: print the catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"
  