[mongodb]
mongodb.thiscomeback.fun

[redis]
redis.thiscomeback.fun

[mysql]
mysql.thiscomeback.fun

[rabbitmq]
rabbitmq.thiscomeback.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local]
localhost



