- name: host the redis
  hosts: redis
  become: yes
  tasks:
  - name: disbale default redis
    ansible.builtin.command: dnf module disable redis -y

  - name: enble redis 
    ansible.builtin.command: dnf module enable redis -y

  - name: install redis
    ansible.builtin.package:
      name: redis
      state: present

  - name: all remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.config
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disbale protection mode
    anisble.builtin.lineinfile:
     path: /etc/redis/redis.config
     regexp: 'protected-mode'
     line: 'protected-mode no'


  - name: start and enable the service
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes
    